'use server';

import { env } from 'cloudflare:workers';
import type { Env } from '../types/env';
import { getSettings } from '../utils/kv-storage';
import { createLogger } from '../utils/logger';

const logger = createLogger();

/**
 * Preview machines matching a selector
 */
export async function previewMachineSelectorAction(selector: { field: string; pattern: string }) {
    try {
        const cfEnv = env as Env;
        const ownerId = cfEnv.DNS_RECORD_OWNER_ID;

        // Load settings to get Tailscale credentials (don't validate full schema, just extract credentials)
        const rawSettings = await getSettings(cfEnv.CONFIG_KV, ownerId);
        const apiKey = rawSettings.TAILSCALE_API_KEY;
        const tailnet = rawSettings.TAILSCALE_TAILNET;

        if (!apiKey || !tailnet) {
            return {
                success: false,
                error: 'Tailscale credentials not configured. Please set up credentials first.',
            };
        }

        // Fetch Tailscale devices
        const { TailscaleClient } = await import('../services/tailscale-client');
        const tsClient = new TailscaleClient({
            apiKey,
            tailnet,
        });
        const devices = await tsClient.getDevices();

        // Apply selector
        const { selectMachines } = await import('../utils/machine-selector');
        const matches = selectMachines(devices, selector);

        // Return preview data
        return {
            success: true,
            matches: matches.map((match) => ({
                name: match.device.name,
                hostname: match.device.hostname,
                tags: match.device.tags || [],
                captures: match.captures || {},
            })),
            totalDevices: devices.length,
            matchedDevices: matches.length,
        };
    } catch (error) {
        logger.error('Preview machine selector error via Server Action:', error);
        return {
            success: false,
            error: error instanceof Error ? error.message : String(error),
        };
    }
}

/**
 * Preview DNS records that would be generated by a task
 */
export async function previewTaskRecordsAction(taskData: {
    machineSelector: { field: string; pattern: string };
    recordTemplates: any[];
}) {
    try {
        const cfEnv = env as Env;
        const ownerId = cfEnv.DNS_RECORD_OWNER_ID;

        // Load settings to get Tailscale credentials and CIDR lists (don't validate full schema)
        const rawSettings = await getSettings(cfEnv.CONFIG_KV, ownerId) as any;
        const apiKey = rawSettings.TAILSCALE_API_KEY;
        const tailnet = rawSettings.TAILSCALE_TAILNET;

        const namedCIDRLists = rawSettings.namedCIDRLists || [];

        if (!apiKey || !tailnet) {
            return {
                success: false,
                error: 'Tailscale credentials not configured. Please set up credentials first.',
            };
        }

        // Fetch Tailscale devices
        const { TailscaleClient } = await import('../services/tailscale-client');
        const tsClient = new TailscaleClient({
            apiKey,
            tailnet,
        });
        const devices = await tsClient.getDevices();

        // Apply selector
        const { selectMachines } = await import('../utils/machine-selector');
        const matches = selectMachines(devices, taskData.machineSelector);

        // Generate preview records
        const previewRecords: any[] = [];
        const { evaluateTemplate } = await import('../utils/template-engine');

        for (const match of matches.slice(0, 5)) { // Limit to first 5 for preview
            const context: any = {
                machineName: match.device.hostname || match.device.name,
                tailscaleIP: match.device.addresses?.[0] || '',
                tags: match.device.tags || [],
                captures: match.captures || {},
                namedCIDRLists: namedCIDRLists,
                device: match.device,
            };

            for (const template of taskData.recordTemplates) {
                try {
                    const nameResult = evaluateTemplate(
                        template.name,
                        context
                    );
                    const valueResult = evaluateTemplate(
                        template.value,
                        context
                    );

                    // Use the values from results
                    const names = nameResult.values;
                    const values = valueResult.values;

                    // Generate records for all combinations
                    for (const name of names) {
                        for (const value of values) {
                            const record: any = {
                                machine: match.device.name,
                                recordType: template.recordType,
                                name: name,
                                value: value,
                                ttl: template.ttl || 3600,
                                proxied: template.proxied || false,
                            };

                            if (template.recordType === 'SRV') {
                                record.priority = template.priority ?? 10;
                                record.weight = template.weight ?? 10;
                                record.port = template.port ?? 80;
                            }

                            previewRecords.push(record);
                        }
                    }
                } catch (error) {
                    logger.warn('Template evaluation error in preview:', error);
                }
            }
        }

        return {
            success: true,
            records: previewRecords,
            totalMatches: matches.length,
            previewLimit: Math.min(matches.length, 5),
        };
    } catch (error) {
        logger.error('Preview task records error via Server Action:', error);
        return {
            success: false,
            error: error instanceof Error ? error.message : String(error),
        };
    }
}
